name: Update Wiki

permissions:
  contents: "write"

on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [.github/wiki/**, .github/workflows/docs.yml]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Generate docs
        run: yarn generate-docs
      - name: "Set environmental variables"
        run: |
          echo "ACTION_MAIL=$GITHUB_ACTOR@users.noreply.github.com" >> $GITHUB_ENV
          echo "ACTION_NAME=$GITHUB_ACTOR" >> $GITHUB_ENV
      - name: Upload docs to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          OWNER: owowagency
          REPO_NAME: gsap-motion
          MD_FOLDER: .github/wiki
