name: Update Wiki

permissions:
  contents: "write"

on:
  push:
    branches: [main]
    tags: ["*"]
    paths: [.github/wiki/**, .github/workflows/docs.yml]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Generate docs
        run: yarn generate-docs
      - name: Clone wiki repository
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/owowagency/gsap-motion.wiki.git wiki
          cd wiki
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote rm origin
      - name: Copy documentation markdown files
        run: cp -R .github/wiki/* wiki/
      - name: Commit and push changes
        run: |
          cd wiki
          git add .
          git commit -m "Update documentation"
          git push
