name: Publish

permissions:
  contents: "write"

on:
  push:
    branches: [main]
    tags: ["*"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Detect package manager
        id: detect-package-manager
        run: |
          echo "manager=yarn" >> $GITHUB_OUTPUT
          echo "command=install" >> $GITHUB_OUTPUT
          echo "runner=yarn" >> $GITHUB_OUTPUT
          exit 0

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build
        run: yarn build

      - name: Update wiki
        run: |
          yarn generate-docs --out temp_wiki
          git clone https://$GITHUB_ACTOR:${{ secrets.GH_PAT }}@github.com/owowagency/gsap-motion.wiki.git wiki
          cd wiki
          rm -rf *
          cd ..
          cp -R temp_wiki/* wiki
          cd wiki
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add .
          git commit -m "Update documentation"
          git push
