name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Run ESLint on changed files
        run: git diff --name-only origin/${{ github.base_ref }} HEAD | xargs npx eslint
